version: '2'

services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ADMIN_DB
    volumes:
       - data:/data
    ports:
        - "5432:5432"
    restart: unless-stopped
  
  pgadmin:
    links:
      - postgres:postgres
    image: fenglc/pgadmin4
    
    ports:
        - "5050:5050"
    restart: unless-stopped

volumes:
    data:
        external: false

